name: test pipeline manuel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
         # Déclenchement manuel activé !

jobs:
  test-manual:
    runs-on: ubuntu-latest # Correction : avec le 't' à la fin

    steps:
      - name: Lancement du script
        run: echo "deploiement de l'application sur ${{ inputs.environment }}"