name: test pipeline

on:
  push:
    branches:
      - main
    paths:
      - "test.py" # Chemin relatif par rapport à la racine du dépôt Git !

jobs:
  test_workflow:
    runs-on: ubuntu-latest # Correction de l'orthographe d'Ubuntu

    steps:
      - name: first step
        uses: actions/checkout@v7.0.0
          
      - name: affichage 
        run: echo "hello world"
        if: ${{ github.event_name == 'push' && github.event.head_commit.message == 'BIG'}} # Syntaxe sur une seule ligne propre