name: pull test

on:
    pull_request:
        branches: [main]

jobs:
    job-1:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: test 
              uses: actions/setup-python@v6
            
            - run: python test.py