name: gemini gmail

on:
    pull_request:
        branches: [main]

jobs:
    job-1:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: test 
              uses: actions/setup-python@v6
            
            - run: python test.py

            - name: mail envoye
              run: |
                  curl -X POST https://notify.run/c/xmjsN8u2nBv4JiSAAAHi \
                  -d "message=✅ Succès : L'image Docker a été buildée par ${{ github.actor }} !"   